Insert Into Laptop(company,hard_disk_size,processor,ram_size,number_of_drives,owner,price)
values('HP','160GB','Core i5','8GB',4,'Surendra',52999.00)
Insert Into Laptop(company,hard_disk_size,processor,ram_size,number_of_drives,owner,price)
values('HP','80GB','Core i3','4GB',3,'Nadh',43999.00)
Insert Into Laptop(company,hard_disk_size,processor,ram_size,number_of_drives,owner,price)
values('HP','120GB','Core i7','6GB',3,'Kapa',45900.00)
Insert Into Laptop(company,hard_disk_size,processor,ram_size,number_of_drives,owner,price)
values('DELL','160GB','Core i5','8GB',4,'Naga',53999.00)
Insert Into Laptop(company,hard_disk_size,processor,ram_size,number_of_drives,owner,price)
values('DELL','120GB','Core i5','6GB',3,'Phanidra',42889.00)
Insert Into Laptop(company,hard_disk_size,processor,ram_size,number_of_drives,owner,price)
values('DELL','80GB','Core i3','4GB',2,'Vunnava',34700.00)
Insert Into Laptop(company,hard_disk_size,processor,ram_size,number_of_drives,owner,price)
values('ASUS','160GB','Core i7','8GB',4,'Srini',55779.00)
Insert Into Laptop(company,hard_disk_size,processor,ram_size,number_of_drives,owner,price)
values('ASUS','120GB','Core i5','6GB',3,'vasu',42889.00)
Insert Into Laptop(company,hard_disk_size,processor,ram_size,number_of_drives,owner,price)
values('ASUS','80GB','Core i3','4GB',2,'Mani',29889.00)
Insert Into Laptop(company,hard_disk_size,processor,ram_size,number_of_drives,owner,price)
values('Apple','160GB','Core i7','8GB',4,'Dharma',51889.00)
Insert Into Laptop(company,hard_disk_size,processor,ram_size,number_of_drives,owner,price)
values('Apple','120GB','Core i5','6GB',3,'Teja',45749.00)
Insert Into Laptop(company,hard_disk_size,processor,ram_size,number_of_drives,owner,price)
values('Apple','80GB','Core i3','4GB',2,'Babu',38932.00)
